services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # Management UI port

  invoice-service:
    build: ./invoice-service
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - rabbitmq
